export const places = [
	{
		name: "geli ali beg waterfall",
		image: "../assets/Geli_Ali_Beg_Waterfall.jpg",
		location: "Erbil",
		rating: "4.5",
		alwaysOpen: true,
		touristsNum: "6M",
	},
	{
		name: "Ahwar of Southern Iraq",
		image: "../assets/ahwar.jpg",
		location: "Dhi Qar Governorate",
		rating: "4.4",
		alwaysOpen: true,
		touristsNum: "3K",
	},
	{
		name: "Ash-Shinafiyah",
		image: "../assets/ash_shinafiyah.jpg",
		location: "Al-Qādisiyyah Governorate",
		rating: "4.6",
		alwaysOpen: true,
		touristsNum: "20K",
	},
	{
		name: "Virgin Mary's Chaldean Catholic Church",
		image: "../assets/virgin_mary_church.jpg",
		location: "Baghdad",
		rating: "4.6",
		alwaysOpen: true,
		touristsNum: "5K",
	},
	{
		name: "Erbil Castle",
		image: "../assets/erbil_castle_card.jpg",
		location: "Erbil",
		rating: "4.4",
		openTime: "09:00 AM",
		closeTime: "07:00 PM",
		touristsNum: "1.75M",
	},
	{
		name: "Malwiya Mosque",
		image: "../assets/malwiya.jpg",
		location: "Saladin, Samarra",
		rating: "4.4",
		openTime: "09:00 AM",
		closeTime: "05:00 PM",
		touristsNum: "8K",
	},
	{
		name: "Ancient Babylon",
		image: "../assets/ancient_babylon.jpg",
		location: "Babylon",
		rating: "4.4",
		openTime: "09:00 AM",
		closeTime: "09:30 PM",
		touristsNum: "25.7K",
	},
	{
		name: "Abu Hanifa Mosque",
		image: "../assets/abu_hanifa_mosque.jpg",
		location: "Baghdad",
		rating: "4.4",
		alwaysOpen: true,
		touristsNum: "2K",
	},
	{
		name: "Imam Ali Holy Shrine",
		image: "../assets/imam_ali.jpeg",
		location: "Najaf",
		rating: "4.8",
		alwaysOpen: true,
		touristsNum: "18M",
	},
];
